# Generated by Django 3.0.5 on 2020-04-18 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirewallConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('hostname', models.CharField(max_length=50)),
                ('api_key', models.CharField(max_length=128)),
                ('panorama', models.BooleanField()),
            ],
        ),
    ]
