# Generated by Django 3.0.5 on 2020-04-18 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_paloalto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firewallconfig',
            name='api_key',
            field=models.CharField(max_length=255),
        ),
    ]
